### ISSUE TITLE
Copy planing info for the group5

### ISSUE THREAD

**Issue by andriivam** [lab-brussels-1/group5#1]
This feature developed in the branch `1-update`
- [ ] Add the files from class repo to the group repo
- [ ] Add the information of files needed
- [ ] Properly committed the updates
- [ ] Run all the rpm checks
- [ ] Pushed the changes to main branch
- [ ] I have created PR and assigned someone to review it
- [ ] Merged to the main branch

**Comment by bermarte** [comment]
Better to name it `1-update` or `1_update`. Don't forget to add the checks, eg. `npm run formta` and so on but **before** the commit.
